### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by lburgazzoli**
- chore: upgrade quarkus to v2.6.0.Final
- chore: upgrade cucumber to v7.1.0
- chore: upgrade quarkiverse-parent to v9

### CODE REVIEW

**Comment by gsmet** [comment]
Hum. This repository is part of the repositories where we have a dependabot.yml file but dependabot is not activated.

I'll merge this and I'll fix Dependabot.

**Review by gsmet — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@gsmet any chance to get a new release of this extension ?

**Comment by gsmet** [comment]
I'll give some love to the repository and do that today.

**Comment by lburgazzoli** [comment]
thx so much

**Comment by gsmet** [comment]
@lburgazzoli 0.5.0 is available on Maven Central.

**Pull request merged**
