### PR TITLE
add support of beforeall and afterall hooks

### PR DESCRIPTION
**Pull request by tbounsiar**
Adding support of `@BeforeAll()` and `@AfterAll() `
Issue https://github.com/quarkiverse/quarkus-cucumber/issues/79

### CODE REVIEW

**Comment by tbounsiar** [comment]
#19 Hi all, can you take a look please
thank you

**Comment by christophd** [comment]
Thanks! It would be good to have a unit test that verifies that the Cucumber Before/After hook gets called once before/after all tests

**Comment by tbounsiar** [comment]
> Thanks! It would be good to have a unit test that verifies that the Cucumber Before/After hook gets called once before/after all tests

Done by using configurable fake Factory in basic test.

**Comment by bmscomp** [comment]
LGTM

**Pull request merged**
