### PR TITLE
Upgrade the version of cucumber to 7.15.0

### PR DESCRIPTION
**Pull request by bmscomp**
Upgrading the version of cucumber to the last stable version 7.15.0 can bring bug fixing and performance improvements since the last version used in the library 

For more details please refer to https://github.com/cucumber/cucumber-jvm/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by bmscomp** [comment]
@gastaldi  There is already a released stable version 7.15.0 I think it worth to bring it with this pull request

**Comment by bmscomp** [comment]
Please any one can consider merging this pull request, I think it's pretty stable

**Comment by gastaldi** [comment]
@all-contributors add @bmscomp for code

**Comment by bmscomp** [comment]
@gastaldi  Yes, and I'll be glad for that

**Pull request merged**
